### ISSUE TITLE
Agent process on a persistent worker exited unexpectedly on macOS

### ISSUE THREAD

**Issue by ligurio** [cirruslabs/cirrus-ci-agent#107]
sometimes build failed because worker exited unexpectedly

`cirrus-ci.yml` - https://github.com/ligurio/unreliablefs/blob/master/.cirrus.yml#L53
Example: https://cirrus-ci.com/task/4845006646149120

**Comment by fkorotkov** [comment]
Worker `y9-6` got corrupted and unregistered `big-sur-base` VM so it was failing to start. It's fixed now. Sorry for the inconveniences.
