### ISSUE TITLE
Ability to share environment variables between task's scripts

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/cirrus-ci-agent#139]
See https://github.com/cirruslabs/cirrus-ci-docs/issues/840.

**Comment by fkorotkov** [comment]
Please document it too in cirrus-ci-docs

**Comment by edigaryev** [comment]
> Please document it too in cirrus-ci-docs

Sure, will fix this in https://github.com/cirruslabs/cirrus-ci-docs/issues/840.
