### ISSUE TITLE
Migrate to new google.golang.org/protobuf package

### ISSUE THREAD

**Issue by edigaryev** [cirruslabs/cirrus-ci-agent#14]
Reasons why in the [golang/protobuf](https://github.com/golang/protobuf)'s README.md:

>It has been superseded by the [`google.golang.org/protobuf`](https://pkg.go.dev/mod/google.golang.org/protobuf) module, which contains an updated and simplified API, support for protobuf reflection, and many other improvements. We recommend that new code use the `google.golang.org/protobuf` module.

The old package is used here: https://github.com/cirruslabs/cirrus-ci-agent/blob/be16e8eb09aa18362dde11b8f3e7a2e9de25d7c2/api/cirrus_ci_service.pb.go#L9

This usage results in the following linter error:

>SA1019: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (staticcheck)

**Comment by edigaryev** [comment]
This seems to be still WIP on the gRPC's side: https://github.com/grpc/grpc.io/issues/298

**Comment by fkorotkov** [comment]
Yeah, I tried to generate the stubs but they still use the old one. 🤷

**Comment by edigaryev** [comment]
This issue was a bit misplaced by the Cirrus CLI's usage of `github.com/cirruslabs/cirrus-ci-agent/api` package and will be fixed in https://github.com/cirruslabs/cirrus-cli/pull/26.

As for this repo — we don't directly use the old Protocol Buffers package here except for the code generated by `protoc` (https://github.com/golang/protobuf/issues/1077), but there's already exist a workaround for that in `stacticcheck` (https://github.com/dominikh/go-tools/commit/7e758a3887f90d0ded5f0446112616758183866b).
