### ISSUE TITLE
Support uploading artifacts outside of the working directory

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-agent#197]
Right now it's only possible to upload artifacts which are inside the working directory. Let's support uploading arbitrary files and folders.

I think, in case the agent sees files outside of the working directory in the list for an upload, it should find the longest common prefix and upload the files relative to that folder.

**Comment by edigaryev** [comment]
Related: https://github.com/cirruslabs/cirrus-ci-docs/discussions/946.
