### ISSUE TITLE
Fetch failed: reference delta not found!

### ISSUE THREAD

**Issue by dpo** [cirruslabs/cirrus-ci-agent#201]
Hi, I hope this is the right place to report this issue. We keep getting
```
Fetch failed: reference delta not found!
```
on a handful on repos from our organization, and a bit at a loss to determine what the cause may be. I would greatly appreciate any ideas or suggestions.

https://cirrus-ci.com/task/4904675521593344

Many thanks in advance!

**Comment by edigaryev** [comment]
Will close this once the fix is deployed.

**Comment by fkorotkov** [comment]
It got deployed this morning.

**Comment by dpo** [comment]
Many thanks!
