### ISSUE TITLE
RFE: auto restart for "Failed to start java blah"

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-ci-agent#303]
Quite often we submit PRs, come back an hour later, and find:

>! Failed to start: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7d6a9ed9[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@47426c98[Wrapped task = TrustedListenableFutureTask@6ef275bf[status=PENDING, info=[task=[running=[NOT STARTED YET], com.google.api.gax.rpc.CheckingAttemptCallable@17b03199]]]]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@29980b40[Shutting down, pool size = 4, active threads = 0, queued tasks = 2, completed tasks = 1523]

A hooman then has to manually click Re-run on all of those. And wait an extra hour.

Would it be possible to auto-restart these? Perhaps after a binary backoff?

Thank you!

**Comment by edsantiago** [comment]
[Example](https://cirrus-ci.com/task/5344443331510272). And [another](https://cirrus-ci.com/task/6048130773286912) on the same CI run. And [one more](https://cirrus-ci.com/task/5913990354698240).

**Comment by edsantiago** [comment]
And [here](https://cirrus-ci.com/task/4668739396829184) and [here](https://cirrus-ci.com/task/5935376792027136) and [here](https://cirrus-ci.com/task/6498326745448448)

**Comment by fkorotkov** [comment]
This should be fixed now! Sorry for the inconveniences and thank you for reporting!

**Comment by edsantiago** [comment]
Thank you so much @fkorotkov !
