### ISSUE TITLE
Add support for retrieving JSON documents with VAULT[] syntax

### ISSUE THREAD

**Issue by elrzn** [cirruslabs/cirrus-ci-agent#304]
Hi!

Currently, trying to retrieve a secret stored as a JSON document instead of a string will raise the following error:

```
Vault-boxed value has an invalid format: selector's element "secret" should point to a string.
```

Since Vault has native support for storing secrets as JSON documents, it would be a great QoL feature to have. This makes sense for example when using GCP service accounts, without having to encode them, which would make version controlling of secrets more difficult.

I personally wouldn't mind something like `VAULT_JSON[...]` if it helps to make the implementation easier.

**Comment by edigaryev** [comment]
Reopening since the changes are not deployed yet.

**Comment by fkorotkov** [comment]
It got rolled out. 👌
