### ISSUE TITLE
Investigate faster alternatives to archiving of caches.

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-agent#50]
Maybe it will be easy to migrate to https://github.com/mholt/archiver since it can do multi-threaded tar.gz compression as well as streaming compression.

**Comment by lygstate** [comment]
may also using zstd, slower compress speed, but very fast extract speed

**Comment by fkorotkov** [comment]
It won't be a backward compatible change but if the performance will be still not good we might add it as an option for the Cache instruction to choose a compression algorithm.
