### ISSUE TITLE
CIRRUS_LOG_TIMESTAMP Behavioral Environment Variable

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-agent#67]
See https://github.com/cirruslabs/cirrus-ci-docs/issues/557 for the details. Even though it's possible to use 3rdparty `ts` from moreutils it will be great to have an option to prefix log lines with timestamp on the agent side via `CIRRUS_LOG_TIMESTAMP: true` [Behavioral Environment Variable](https://cirrus-ci.org/guide/writing-tasks/#behavioral-environment-variables). Not all the environments have moreutils (for example, our macOS VM don't have it preinstalled)

The time format can be similar to [`StampMilli`](https://godoc.org/time#pkg-constants) but without the date (`15:04:05.000`) since we know when the task was created.

Then logs will look like

```
15:04:05.000 Hello, world!
15:04:05.000 sleep 10
15:04:15.000 Hello again!
```

**Comment by RDIL** [comment]
2 things:
1. It would look better to put the time in square brackets
2. It might be better to have this opt-in with an environment variable
