### ISSUE TITLE
Secured variables retain their encrypted values in PRs from unauthorized users

### ISSUE THREAD

**Issue by erikarvstedt** [cirruslabs/cirrus-ci-agent#89]
In PRs from unauthorized users secured variables retain their original encrypted value (with format `ENCRYPTED[...]`).
Instead, the variables should be unset, like in other CI systems like Travis.
This caused a bug in [our](https://github.com/fort-nix/nix-bitcoin/) CI tests after migrating from travis.

The unusual encrypted variable values can easily cause errors in the programs that use them, which would not happen if the variables were just unset.
Also, often the task scripts must check whether a variable is available in the unencrypted form or not. Retaining the encrypted value makes this check needlessly hard.

**Comment by fkorotkov** [comment]
Great suggestion! Should be fixed now and the unencrypted variables will be unset.
