### ISSUE TITLE
Regression: Secured variables retain their encrypted values in PRs from unauthorized users

### ISSUE THREAD

**Issue by erikarvstedt** [cirruslabs/cirrus-ci-agent#96]
The bug described in https://github.com/cirruslabs/cirrus-ci-agent/issues/89 has reappeared.

See https://github.com/erikarvstedt/cirrus-test for an example:
In a [task for a commit](https://cirrus-ci.com/task/6477495291609088) by an unauthorized user, the encrypted variable `TEST_VAR` has value `ENCRYPTED[09b...]`, but should be unset instead.
In a [task for a commit](https://cirrus-ci.com/task/6593294320795648) by the repo owner, the value is successfully decrypted.

**Comment by fkorotkov** [comment]
Indeed! In this case Cirrus didn't even to try to decrypt and  filter out variables. Should be fixed now! Sorry for the inconvenience. 🙌
